### ISSUE TITLE
GrammaticalRelations->Alignment->SyntacticDomainCondition defined as value-list, but no values defined

### ISSUE THREAD

**Issue by xrotwang** [autotyp/autotyp-data#25]
GrammaticalRelations->Alignment->SyntacticDomainCondition has `data: value-list`, but the metadata ha no `values` field:
https://github.com/autotyp/autotyp-data/blob/88133f01232702659bac179baafbb99d3adc1727/metadata/GrammaticalRelations/Alignment.yaml#L872-L880

**Comment by xrotwang** [comment]
Same for GrammaticalRelations GrammaticalRelations SyntacticDomainCondition

**Comment by tzakharko** [comment]
That is because there are no values in the data (all of them are missing). The current GR aggregation scripts only consider GRs that are not bound by syntactic domain conditions, so the variable is there but always NA/NULL. We should maybe report these cases better in the metadata. #30 tracks the overall metadata reporting problem for `value-list` data, so I suggest the discussion of this and related problems continues there.
